import { usePage } from '~/core'

import styles from '~/styles/pages/dashboard.module.scss'

const DashboardPage = () => {
  return usePage({
    head: {
      title: 'Create Next App',
      description: 'Generated by create next app',
    },
    auth: true,
    template: (context) => (
      <main className={styles.dashboardPageWrapper}>
        <div className={[styles.dashboardPageInner].join(' ')}>
          <div>
            {/* empty */}
          </div>
          <div>
            {/* data */}
          </div>
        </div>
      </main>
    ),
  })
}

export default DashboardPage
