import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { createPage } from "~/core/createPage"

import styles from '~/styles/pages/dashboard.module.scss'

const DashboardPage = () => {
  const router = useRouter();

  useEffect(() => {
    // console.log(router)
  })

  return createPage({
    head: {
      title: 'Create Next App',
      description: 'Generated by create next app',
    },
    template: (page) => (
      <main className={styles.dashboardPageWrapper}>
        <div className={[styles.dashboardPageInner].join(' ')}>
          <div>
            {/* empty */}
          </div>
          <div>
            {/* data */}
          </div>
        </div>
      </main>
    ),
  })
}

export default DashboardPage
